config/routes.rb
Henrys::Application.routes.draw do
  
  resources :quotes do
    get :autocomplete_company_name, :on => :collection
  end

  resources :customers
  resources :quotes

  get "customers/new"
  get "customers/index"
  get "pages/dashboard"
  get "quotes/new"
  get "quotes/current_quotes"
  get "quotes/past_quotes"
  get "quotes/index"
  get "home/index"
  get "dashboard/index"

  root 'dashboard#index'

end

app/models/customer-quote.rb
class CustomerQuote < ActiveRecord::Base
  belongs_to :customers
  belongs_to :quote

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :quotes
  
end

app/models/dashboard.rb
class Quote < ActiveRecord::Base
  belongs_to :customers
  

end

app/models/quote.rb
class Quote < ActiveRecord::Base
belongs_to :customers
  validates :company_name, :presence => true
  validates :quote_information, :presence => true
  
  #def company_name
    #customers.try(:company_name)
  #end
  
  #def company_name=(company_name)
    #self.customers = Customer.find_by_company_name(company_name) if company_name.present?
  #end
  
end

app/models/search_suggestion.rb
class SearchSuggestion < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]
  autocomplete :company_name, :full => true
  
  # GET /customers
  # GET /customers.json
  def index
    @customer = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @customer }
      else
        format.html { render action: 'new' }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:company_name, :primary_contact_name, :primary_contact_phone, :primary_contact_email, :primary_contact_address_city_state_zip, :billing_contact_name, :billing_contact_phone, :billing_contact_email, :billing_contact_address_city_state_zip, :install_contact_name, :company_division_sub, :customer_state)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    # @quote = Quote.all
    @quote = Quote.all
    
    # HERE <----    
    # @yesterday_quotes = Quote.where(created_at: (Time.now.midnight - 1.day)) # Load yesterday's quotes here
    @to_be_shipped = Quote.where(order_ship_date: (Time.now.midnight.strftime('%Y-%m-%d'))) # Load today's quotes here
    @quotes_due  = Quote.where(quote_due_date: (Time.now.midnight.strftime('%Y-%m-%d'))) # Load tomorrow's quotes here
  end
  
end

app/controllers/date_controller.rb
class DateRange
  def self.today
    (Time.now.midnight)..Time.now.end_of_day
  end
 
  def self.yesterday
    (Time.now.midnight - 1.day)..Time.now.end_of_day
  end
 
  def self.tomorrow
    (Time.now.tomorrow)..Time.now.end_of_day
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]
  autocomplete :customer, :company_name, :full => true

  before_filter :check_for_cancel, :only => [:create, :update]

  def check_for_cancel
    if params[:commit] == "Cancel"
      redirect_to quote_path
    end
  end
  
  # GET /quotes
  # GET /quotes.json
  def index
    @quote = Quote.all
    @quote = Quote.order(params[:sort])
    # Quote.where(created_at: (Time.now.midnight - 1.day)..Time.now.midnight)
  end
  
  #def timestamp
    #self[:timestamp] ||= Time.parse("#{self[:created_date].strftime("%Y-%m-%d")}")
    # @quote_by_date = @quote.group_by(&:created_at)
    # @date = params[:date] ? Date.parse(params[:date]) : Date.tomorrow
  #end  
  
  def edit
    @quote = Quote.find params[:id]
  end
  

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render action: 'show', status: :created, location: @quote }
      else
        format.html { render action: 'new' }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    @quote = Quote.find(params[:id])
    @quote.update_attributes(quote_params)
    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render action: 'show', status: :created, location: @quote }
      else
        format.html { render action: 'new' }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:company_name, :quote_information, :quote_amount, :quote_due_date, :artwork_due_date, :artwork_proof_link, :production_notes, :quote_status, :quote_link, :order_ship_date, :order_installation_date)
    end
end

app/controllers/search_suggestions_controller.rb
class SearchSuggestionsController < ApplicationController
  def index
    render json: %w[foo bar]
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/search_suggestions_helper.rb
module SearchSuggestionsHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <section id="main-content">
      <div id="guts">
        <div id="project">
          <h2><%= f.label :company_name %>: <%= f.text_field :company_name %></h2>
        </div>
        <div id="customer-demographics">
          <h2 class="page-title">Primary Details</h2>
          <%= f.label :primary_contact_name, "Primary Contact Name: " %><%= f.text_field :primary_contact_name %>
          <br><%= f.label :primary_contact_phone, "Primary Contact Phone: " %><%= f.text_field :primary_contact_phone %>
          <br><%= f.label :primary_contact_email, "Primary Contact Email: " %><%= f.text_field :primary_contact_email %>
          <br><%= f.label :primary_contact_address_city_state_zip, "Primary Contact Address: " %><%= f.text_field :primary_contact_address_city_state_zip %>
        </div>
      </div>

      <div id="job-desc">
        <h2 class="page-title">Billing Details</h2>
        <%= f.label :billing_contact_name, "Billing Contact Name: " %><%= f.text_field :billing_contact_name %>
        <br><%= f.label :billing_contact_phone, "Billing Contact Phone: " %><%= f.text_field :billing_contact_phone %>
        <br><%= f.label :billing_contact_email, "Billing Contact Email: " %><%= f.text_field :billing_contact_email %>
        <br><%= f.label :billing_contact_address_city_state_zip, "Billing Contact Address: " %><br><%= f.text_field :billing_contact_address_city_state_zip %>
        <div class="field">

        </div>
      </div>

      <div id="dates"><h2 class="page-title">Customer Details</h2>
        <%= f.label :install_contact_name, "Install Contact Name: " %><%= f.text_field :install_contact_name %>
        <br><%= f.label :company_division_sub, "Company Division Sub: " %><%= f.text_field :company_division_sub %>
        <br><%= f.label :customer_state, "Status:" %> <%= f.select(:customer_state, options_for_select([['Active', 'Active'], ['Inactive', 'Inactive']])) %>
        <br><%= f.label :created_at, "Created At: " %><%= f.date_field :created_at %>
        <br><%= f.label :updated_at, "Updated At: " %><%= f.date_field :updated_at %>
      </div>
      </span>
      </div>
      <div style="clear:both;"></div>
      <div class="actions">
        <%= f.button :submit %>
      </div>
      </div>

      </div>

      <div style="clear:both;"></div>

      </div>

    </section>

<% end %>

app/views/customers/edit.html.erb
<h1>Update Customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<section id="main-content">
  <div id="guts">

<h1>Listing customers | <span class="new"><%= link_to 'New Customer', new_customer_path %></span></h1>

<% @customer.each do |customer| %>
    <div id="quote">
      <h4>#<%= customer.id %> | <%= customer.company_name %></h4>
      <div style="clear:both;"></div>
        <ul style="width: 250px;list-style-type: none;margin-left: -45px;">
          <li style="float:left;"><%= button_to 'Edit', edit_customer_path(customer) %></li>
          <li style="float:left;"><%= button_to "delete", customer_path(customer), :method=>:delete, :class=>:destroy %></li>
          <li style="float:left;"><%= button_to 'View Quote', customer %></li>
        </ul>
    </div>
    <% end %>

      </div>
  </section>

app/views/customers/new.html.erb
<h1 style="text-align:center;">New customer</h1>
<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<section id="main-content">
  <div id="guts">
    <div id="project">
      <h2>Company Name: <%= @customer.company_name %></h2>
    </div>
    <div id="customer-demographics">
      <h2>Primary Details</h2>
      <br>Primary Contact Name: <%= @customer.primary_contact_name %>
      <br>Primary Contact Phone: <%= @customer.primary_contact_phone %>
      <br>Primary Contact Email: <%= @customer.primary_contact_email %>
      <br>Primary Contact Address: <%= @customer.primary_contact_address_city_state_zip %>
    </div>
  </div>

  <div id="job-desc">
    <h2>Billing Details</h2>
    <br>Billing Contact Name: <%= @customer.billing_contact_name %>
    <br>Billing Contact Phone: <%= @customer.billing_contact_phone %>
    <br>Billing Contact Email: <%= @customer.billing_contact_email %>
    <br>Billing Contact Address: <%= @customer.billing_contact_address_city_state_zip %>
    <div class="field">

    </div>
  </div>

  <div id="dates"><h2>Customer Details</h2>
    Install Contact Name: <%= @customer.install_contact_name %>
    <br>Company Division Sub: <%= @customer.company_division_sub %>
    <br>Customer State: <%= @customer.customer_state %>
    <br>Created At: <%= @customer.created_at %>
    <br>Updated At: <%= @customer.updated_at %>
  </div>
  </span>
  </div>
  <div style="clear:both;"></div>
  <div class="actions">
    <%= link_to 'Edit', edit_customer_path(@customer) %> |
    <%= link_to 'Back', customers_path %>
  </div>
  </div>

  </div>

  </div>

</section>

app/views/dashboard/index.html.erb
<section id="main-content">
  <div id="guts">

    <nav>
      <ul class="group">
        <li><%= link_to 'New Quote', 'quotes/new' %></li>
        <li><%= link_to 'Show Quotes', 'quotes' %></li>
        <div style="clear:both;"></div>
      </ul>
    </nav>
    


    <div id="col2" style="text-align:center;">
      <h2>Today - <%= Time.now.strftime("%B %d, %Y") %></h2> 
      
      <div class="quotes-due">
        <h3>Quotes Due</h3>
        <% @quotes_due.each do |quote_due| %>
            #<%= quote_due.id %> <%= quote_due.company_name %> <%= link_to 'View', quote_due %> <br>
         <% end %>
      </div>
      
      <div class="to-be-shipped">
        <h3>To Be Shipped</h3>
        <% @to_be_shipped.each do |shipped| %>
            #<%= shipped.id %> <%= shipped.company_name %> <%= link_to 'View', shipped %> <br>
         <% end %>
      </div>
      <div style="clear:both;"></div>
    </div>
       
       

  
  </div>

  <div style="clear:both;"></div>

  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Henrys</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <script src="http://code.jquery.com/jquery.js"></script>


  <!-- Bootstrap -->
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <link href="stylesheets/bootstrap.css" rel="stylesheet" media="screen">
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "autocomplete-rails.js" %>
  <script src="javascripts/bootstrap.min.js"></script>

  <%= csrf_meta_tags %>

</head>
<body>

<h1>HENRY v1.0</h4>
  <h2 style="text-align:center;font-weight:600;"><a href="http://henry-dgs.herokuapp.com/">Home</a></h2>

<%= yield %>

</body>
</html>

app/views/quotes/_form.html.erb
<%= form_for(@quote) do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <section id="main-content">
      <div id="guts">
        <div id="project">

              <span class="quote">
                <%= f.select :company_name, Customer.all.map { |u| [u.company_name, u.company_name] }, { include_blank: true }, { class: 'chosen-select' } %>
                <%= link_to "New Customer", "", :onclick => "javascript:window.open('/customers/new','popup','width=960,height=900,scrollbars=yes');" %>
                <%= f.label :quote_status, "Status:", style: 'margin-left:110px' %> <%= f.select(:quote_status, options_for_select([['New', 'New'], ['Open', 'Open'], ['Approved', 'Approved'], ['Closed', 'Closed']])) %>
                </span>
        </div>

        <div id="customer-demographics">
          <h2><%= f.label :quote_information, "Quote Information" %></h2>
          <div class="field">
            <%= f.text_area :quote_information, :size => "39x14", class: "notes"  %>
          </div>
        </div>

        <div id="job-desc">
          <h2><%= f.label :production_notes %></h2>
          <div class="field">
            <%= f.text_area :production_notes, :size => "39x14", class: "notes"   %>
          </div>
        </div>

        <div id="dates"><h2 class="page-title">Critical Dates</h2>

          <div class="field">
            <%= f.label :quote_due_date, class: "field_label" %><%= f.date_field :quote_due_date %>
            </div>

          <div class="field">
            <%= f.label :order_ship_date, class: "field_label" %><%= f.date_field :order_ship_date %>
            </div>

          <div class="field">
            <%= f.label :installation_date, class: "field_label" %><%= f.date_field :order_installation_date %>
            </div>

          <div class="field">
            <%= f.label :artwork_due_date, class: "field_label" %><%= f.date_field :artwork_due_date %>
          </div>

          <div class="field">
            <%= f.label :quote_amount, class: "field_label" %><%= f.text_field :quote_amount %>
          </div>

          <div class="field">
            <%= f.label :artwork_proof_link, class: "field_label" %><%= f.text_field :artwork_proof_link %>
          </div>

          <div class="field">
            <%= f.label :quote_link, class: "field_label"  %><%= f.text_field :quote_link %>
            </div>
          
        </div>
        </span>
      </div>
      <div style="clear:both;"></div>
      <div class="actions">
        <%= f.button :submit %>
      </div>
      </div>

      </div>

      <div style="clear:both;"></div>

      </div>

    </section>

<% end %>

app/views/quotes/edit.html.erb
<div style="text-align:center;">
<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %> |
<%= link_to 'Cancel', quote_path %>
<h1>Editing quote</h1>
</div>

<%= render 'form' %>

app/views/quotes/index.html.erb
<nav>
      <ul class="group" style="width: 270px;">
        <li><%= link_to 'New Quote', new_quote_path %></li>
  </ul>
</nav>

<section id="main-content">
  <div id="guts">
      <ul id="sort"> 
        <li><%= link_to "ID", :sort => "id" %></li>
        <li><%= link_to "Company Name", :sort => "company_name" %></li>
        <li><%= link_to "Quote Due Date", :sort => "quote_due_date" %></li>
        <li><%= link_to "Artwork Due Date", :sort => "artwork_due_date" %></li>
        <li><%= link_to "Ship Date", :sort => "order_ship_date" %></li>
        <li><%= link_to "Quote Status", :sort => "quote_status" %></li>
      </ul>
    
<% @quote.each do |quote| %>
      <ul id="sort"> 
        <li>Q#<%= quote.id %></li>
        <li><%= quote.company_name %></li>
        <li><%= quote.quote_due_date %></li>
        <li><%= quote.order_ship_date %></li>
        <li><%= quote.artwork_due_date %></li>
        <li><%= quote.quote_status %></li>
        <div style="clear:both;"></div>
      <%= link_to 'View Quote', quote, :class=>:show %> 
      <%= link_to 'Edit', edit_quote_path(quote), :class=>:edit %> 
      <%= link_to 'Delete', quote_path(quote), :method=>:delete, :class=>:destroy, :confirm => 'Are you sure?' %>
      </ul>
    <% end %>

        </div>

    </section>



<div style="clear:both"></div>

app/views/quotes/new.html.erb
<div style="text-align:center;"><h4><%= link_to 'Back', quotes_path %></h4></div>
<h1 style="text-align:center;">New Quote</h1>

<%= render 'form' %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<section id="main-content">
  <div id="guts">
    <div id="project">
      <h2>Company Name: <%= @quote.company_name %> | Quote Status: <%= @quote.quote_status %></h2>
    </div>
    <div id="customer-demographics">
      <h2>Quote Details</h2>
      <div class="field">
      <%= @quote.quote_information %>
    </div>
  </div>

  <div id="job-desc">
    <h2>Production Notes</h2>
    <div class="field">
      <%= @quote.production_notes %>
    </div>
  </div>

  <div id="dates"><h2>Customer Details</h2>
    Quote Amount: $<%= @quote.quote_amount%>
    <br>Order Ship Date: <%= @quote.order_ship_date %>
    <br>Quote Due Date: <%= @quote.quote_due_date %>
    <br>Artwork Due Date: <%= @quote.artwork_due_date %>
    <br>Artwork Proof Link: <%= link_to 'Link To Artwork Proof', @quote.artwork_proof_link %>
    <br>Order Installation Date: <%= @quote.order_installation_date %>
    <br>Quote Link: <%= link_to 'Link To Quote', @quote.quote_link %>
    <br>Updated At: <%= @quote.updated_at %>
  </div>
  </span>
  </div>
  <div style="clear:both;"></div>
  <div class="actions">
    <%= link_to 'Edit', edit_quote_path(@quote) %> |
    <%= link_to 'Back', quotes_path %>
  </div>
  </div>

  </div>

  </div>

</section>